CREATE TABLE Song 
(
id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY, 
title VARCHAR(100), 
artist VARCHAR(100) NOT NULL, 
label VARCHAR(100),
released INTEGER
);

-- CREATE TABLE tutorials_tbl (
--    id INT NOT NULL,
--    title VARCHAR(50) NOT NULL,
--    author VARCHAR(20) NOT NULL,
--    submission_date DATE,
--    PRIMARY KEY (id) 
-- );