insert into Song(title, artist, label, released) values ("MacArthur Park", "Richard Harris", "Dunhill Records", 1968);
insert into Song(title, artist, label, released) values ("Afternoon Delight", "Starland Vocal Band","Windsong" ,1976 );
insert into Song(title, artist, label, released) values ("Muskrat Love", "Captain and Tennille","A&M" ,1976);
insert into Song(title, artist, label, released) values ("Sussudio","Phil Collins" ,"Virgin",1985 );
insert into Song(title, artist, label, released) values ("We Built This City", "Starship","Grunt/RCA" , 1985);
insert into Song(title, artist, label, released) values ("Achy Breaky Heart","Billy Ray Cyrus" ,"PolyGram Mercury" ,1992 );
insert into Song(title, artist, label, released) values ("What’s Up?", "4 Non Blondes", "Interscope", 1993);
insert into Song(title, artist, label, released) values ("Who Let the Dogs Out?", "Baha Men", "S-Curve", 2000);
insert into Song(title, artist, label, released) values ("My Humps","Black Eyed Peas" ,"Universal Music" , 2005);
insert into Song(title, artist, label, released) values ("Chinese Food", "Alison Gold", "PMW Live", 2013);